#!/usr/bin/env python3
number = 50
if number > 0 and number < 50:
  print("positive smaller than 50")
  if number % 2 == 0:
    print("it is an even number that is smaller than 50")
elif number == 50:
  print("number is exactly 50") 
elif number > 50:
  print("positive and bigger than 50")
  if number % 3 == 0:
    print("it is lsrger than 50 and divisible by 3")
elif number == 0:
  print("equal to zero")
else:
  print("negative")

