#!/usr/bin/env python3
import sys
number = int(sys.argv[1])
if number > 0 and number < 50:
  print(number, "is positive and smaller than 50")
  if number % 2 == 0:
    print(number, " is an even number that is smaller than 50")
elif number == 50:
  print(number, "is exactly 50") 
elif number > 50:
  print(number, "is positive and bigger than 50")
  if number % 3 == 0:
    print(number, " is lsrger than 50 and divisible by 3")
elif number == 0:
  print(number, " is equal to zero")
else:
  print(number," is negative")
